### ISSUE TITLE
Create login page

### ISSUE THREAD

**Issue by elenacoazzoli** [elenacoazzoli/adogtion#2]
- [x] Create Login Next.js page
- [ ] #7
- [ ] Create error messages for server side validation 
- [x] Redirect user to origin page
