### ISSUE TITLE
Create dogs overview page

### ISSUE THREAD

**Issue by elenacoazzoli** [elenacoazzoli/adogtion#5]
TODO: 

- [x] Create individual component for dogs
- [x] Connect to DB
- [x] Fetch data from API
- [x] #16
- [ ] Create function for clustering age of dogs in puppy, young, senior, adult
- [ ] Design component for filter
- [ ] Add filters:
	- [ ] by age 
	- [ ] by gender
	- [ ] by size
	- [ ] by activity
	- [ ] kids and pets
	- [ ] by region
