### ISSUE TITLE
Create dog individual page

### ISSUE THREAD

**Issue by elenacoazzoli** [elenacoazzoli/adogtion#6]
TODOS:

- [ ] Create layout for dog description
- [ ] Populate with dog info and shelter info 
- [ ] Create button for favourites
- [ ] Sponsor section: 
	- [ ] 	Create 3 donations values with 3 buttons 
	- [ ] Checkout page 
- [ ] Adoption section: 
	- [ ] Link to checklist? 
	- [ ] Contact form?
